[pytest]
testpaths = . tests
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*
norecursedirs = .git .tox dist build *.egg .github htmlcov site
addopts =
    --verbose
    --strict-markers
    --tb=short
